

#host: 185.217.131.182
host: localhost


spring:
  datasource:
        url: jdbc:postgresql://localhost:5432/pdp_service_support_bot
        username: postgres
        password: root123
#    url: jdbc:postgresql://${host}:5432/narda_db
#    username: narda
#    password: 009057246
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: on
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          charset: UTF-8
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

  sql:
    init:
      mode: never

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: /home/ubuntu/erp/logs/education/education.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
server:
  port: 7878
